system_test/testToken.js
The test table `ORDERS` is no longer used in the NodeJS tests.
=> not use orders table

.github/workflows/build-test.yml
Set all Windows test jobs to use Python 3.7 since we don't support Python 3.8 right now
=> Set Windows test jobs to use Python 3.7

lib/agent/ocsp_response_cache.js, lib/agent/socket_util.js, lib/global_config.js
By increasing the cache size, cache entries for already retrieved OCSP certificates will no longer be overwritten.
=> Increase OCSP cache size

package.json
=> SNOW-329943: Bumped up the NodeJS Driver PATCH version from 1.6.0 to 1.6.1

Jenkinsfile
SNOW-359281
run semgrep in temp dir to prevent potential issue of .git folder ownership being changed to root
also use new baseline ref parameter to stop reporting issue in upstream branch since current branch was created
=> run semgrep in temp dir and use new baseline ref

package.json
This is to resolve the following issue with a dependency, during webpack builds.
```
ERROR in ./node_modules/when/lib/env.js
Module not found: Error: Can't resolve 'vertx' in '/builds/.../node_modules/when/lib'
```
=> update requestretry to avoid missing package issues on snowflake

package.json
Based on https://github.com/snowflakedb/snowflake-connector-nodejs/issues/275
Some of those dependencies was added in response to critical vulnerabilities that prevented the connector from building. They are now removed since the vulnerability is resolved.
ocsp is being used. test-console and mock-require are used when testing is done and needs to be under dependencies
=> Unused deps

lib/authentication/authentication.js, lib/connection/connection.js, lib/services/sf.js, test/unit/authentication/authentication_test.js
Based on PR https://github.com/snowflakedb/snowflake-connector-nodejs/pull/239 for issue https://github.com/snowflakedb/snowflake-connector-nodejs/issues/222
=> Set 'Client Application' under 'Client Info'

lib/authentication/auth_okta.js
Based on SF #00382081
Issue is due to the given url not containing the closing '/' character which causes the error
`https://testurl.okta.com` vs `https://testurl.okta.com/`
Check against the given url length instead so it works whether the closing '/' character is included
=> Modify okta url length check

package.json
Update mocha to 10.1.0 to resolve dependency vulnerability (https://github.com/advisories/GHSA-f8q6-p94x-37v3) found in https://github.com/snowflakedb/snowflake-connector-nodejs/pull/352
=> Update mocha to version 10.1.0

lib/core.js, test/integration/testConnection.js
Fix for issue raised in #355 .
If using a connection pool and the wrong password/role is specified, the connector gets stuck in an infinite loop instead of returning an error.
The issue is reported on the node-pool module github page: https://github.com/coopernurse/node-pool/issues/273.
And a workaround here https://github.com/coopernurse/node-pool/pull/221.
=> Fix connection pool login retry with incorrect pwd/role

lib/connection/connection.js, test/integration/testConnection.js
Send request to heartbeat endpoint instead of issuing a SELECT 1 query to keep the connection alive.
Resolves #354
=> Send heartbeat call to heartbeat endpoint, instead of SELECT 1

package.json
Based off [PR 391](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/391)
The latest version of `jsonwebtoken@v9.0.0` fixes a number of security issues ranging from `moderate` to `high` severity.
https://github.com/advisories/GHSA-27h2-hvpr-p74q
https://github.com/advisories/GHSA-hjrf-2m68-5959
https://github.com/advisories/GHSA-qwph-4952-7xr6
https://github.com/advisories/GHSA-8cf7-32gw-wr33
=> Bump jsonwebtoken to v9.0.0

lib/agent/socket_util.js
Regarding https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/99
Add error details when logging the OCSP fail open warning message and change log level from 'info' to 'warn'
=> Add error details to OCSP warning message

lib/connection/bind_uploader.js, lib/file_transfer_agent/file_transfer_agent.js, lib/file_transfer_agent/remote_storage_util.js
for issue 66, array binding master key issue.
increased the upload file size (1024 * 1024 * 1024 * 10) to reduce the total number of files which send to the server. The required memory is almost the same, we write all those binding data to the files and upload it. After uploaded those files, the driver will delete it from the memory. 
force smkid to string
=> force smkid to string

lib/agent/https_ocsp_agent.js, lib/agent/https_proxy_ocsp_agent.js, lib/agent/ocsp_response_cache.js, lib/agent/socket_util.js, test/integration/ocsp_mock/https_ocsp_mock_agent.js
Fix for issue: NodeJS driver is not sending ocsp requests through proxies
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/57
The root cause is proxy agent is not used when connect to ocsp server.
To fix the issue, pass in proxy agent for ocsp validation.
No test case added since proxy is not available on github test environment. There is no way to set global proxy setting in nodejs so the trick we used for ODBC, having invalid proxy settings in environment variables, doesn't work either. Confirmed with local test through log (added in HttpsProxyAgent.connect() ) that proxy is used for ocsp validation and connection can be made.
=> apply proxy settings for ocsp validation

lib/util.js, test/unit/util_test.js
Regarding issue 229
Connector will retry when receiving HTTP status 429 (Too Many Requests)
=> Retry the request on HTTP status code 429

lib/agent/ocsp_response_cache.js, lib/agent/socket_util.js, lib/global_config.js, test/integration/testOcsp.js
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/129
The OCSP local cache won't be refreshed if the application run for a long time and the cache is expired during that, so query will fail after that.
The root cause is that the driver only check expiration and refresh the cache when the application start, no refresh logic afterwards.
=> Bug fix: refresh ocsp local cache when expired

lib/agent/ocsp_response_cache.js, lib/global_config.js
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/129
This is further fix for the changes made in [PR#442](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/442)
There was a typo in logging when changing the variable name from cacheUpdateTime to cacheUpdateTimeSec
The test case added in PR#442 didn't work as expected and passed with the bug while the functionality actually did work.
The reason is that the variable maxAgeSec (for the life time of local cache) is initialized when application starts and can't be updated later. So changing environment variable after it's initialized won't work.
Fix the typo, also update maxAgeSec per request to make the test case work.
=> SNOW-727386: bug fix for ocsp cache refresh

lib/services/sf.js, test/unit/mock/mock_http_client.js
Regarding issue 358
When multiple connections are opened using the OAuth authenticator, closing one of those connections lead to the other connections being terminated as well
The PR closes the connection using the session token instead of the master token so that all OAuth connections will not be terminated if one of the connections are closed
=> Use the session token when closing the connection

README.md, lib/connection/connection.js, package.json, test/configureLogger.js, test/integration/testConnection.js
- add optional callback to `connection.heartbeat` function
- unify `connection.heartbeat` and `connection.heartbeatAsync` functions
- add `configureLogger` function to easier turn on the logs in tests
=> SNOW-358605: Unify connection heartbeat functions

lib/connection/connection.js, lib/core.js, test/integration/testConnection.js
Add `connection.isValidAsync` as combination of `connection.isUp` and `connection.heartbeatAsync`
=> SNOW-358605: Add isValidAsync to connection

.github/workflows/cla_bot.yml, lib/file_transfer_agent/file_transfer_agent.js, test/integration/testPutGet.js
issue [175](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/175)
The cause of the issue: uploads uses the metadata from the first file to encrypt, and it also reads from the first file to decrypt for downloads. This method works when uploading files all together and then download them all together. But when uploading files one by one, it will use different encryption material, then it cannot download all the files together. That's why only the first file succedded to download. The fix is to set the download to read the encryption material from each file and make sure all the files has its own encryption material when uploading it.
=> Fix multi-file download 

ci/container/hang_webserver.py, lib/http/base.js, lib/services/large_result_set.js, test/integration/testLargeResultSet.js, test/unit/large_result_set/testLargeResultSet.js
- Add tests for LargeResultSet handing timeout and 503 errors
- handle urllib timeout errors and not OK http response codes in LargeResultSet
- write err or body to callback after all retries in LargeResultSet
=> SNOW-829219: Fix retry in LargeResultSet

ci/container/build_component.sh
Temporary set `npm audit` level to `moderate` until new version of fast-xml-parser is released and its low vulnerability is fixed
=> SNOW-841052: Set moderate on npm audit during ci build

ci/container/build_component.sh
Unintentionally nvm in build phase was included in npm package for testing. This PR move it to ignored by npm directory (in .npmignore).
=> SNOW-841052: Don't put nvm in pack during ci build

ci/container/test_component.sh, ci/test_windows.bat, lib/connection/connection.js, test/integration/testArrayBind.js, test/integration/testConnection.js, test/integration/testStatement.js, test/integration/testUtil.js
- Don't create connection outside of mocha specific methods
- Speed up connection Multiple Client test
- Redirect hang webserver output to the file
- Don't throw exception from default heartbeat callback - there is no handler for it
- Don't write directly to shared connection options
- Set longer delays for cancel array bind test
- Call callback in series and done outside series and remove console logs
- Drop tables after array bind tests
=> SNOW-831683: Fix flaky test

.github/workflows/build-test.yml
- Run CI Build jobs in parallel
- Stop old jobs when PR is updated or branch is updated
- PR contains https://github.com/snowflakedb/snowflake-connector-nodejs/pull/551 to not fail on npm audit
=> SNOW-848733: Run CI builds in parallel

.eslintrc.js, test/integration/testArrayBindCustomerTable.js, test/integration/testPutGet.js, test/integration/testUtil.js
In `testArrayBindCustomerTable` and `testPutGet`:
- retry flaky tests with `mocha` built-in retry mechanism
- format files with `eslint`
- don't call `done` in `async.series` explicitly - use callback instead
- move common setup and teardown operations to before and after to ensure that for errors resources are correctly cleaned up
=> SNOW-831683: Retry and cleanup testPutGet and testArrayBindCustomerTable

.github/workflows/cla_bot.yml
CLA Assistant check has been failing for release branches. The failure is due the jenkins user used to create the branch and do the commit is not in the allow list in that check.
The fix is to add it.
=> SNOW-845753 - Add Jenkins user to allow list for cla assistant check

ci/scripts/set_git_info.sh, ci/test_windows.bat
Let's Windows CI test scripts do not ignore CLOUD_PROVIDER env variable
=> SNOW-852382: Run Windows CI build on azure and gcp

lib/connection/connection.js, lib/connection/statement.js, lib/services/sf.js
=> SNOW-855106: Use correct way to import a uuid library

lib/util.js, test/unit/util_test.js
Accept private key with new lines at the end
=> SNOW-728173: Remove new line for verifier the private key end

lib/connection/result/column.js, lib/core.js, lib/global_config.js, test/integration/testExecute.js
=> SNOW-830291, #506 XMLParser - initialisation with custom configuration

ci/container/hang_webserver.py, test/hangWebserver.js, test/integration/testConnectionWithOCSP.js, test/unit/large_result_set/testLargeResultSet.js
=> SNOW-863058: Explicitly set hang webserver address

lib/global_config.js, test/integration/testExecute.js, test/integration/testPutGet.js
=> SNOW-830291: XmlParser configuration - fix default values.

package.json
Latest word-wrap is released and is automatically downloaded by urllib. we no longer needs to override it.
=> revert word-wrap upgrade

.github/workflows/build-test.yml, Jenkinsfile, ci/container/test_component.sh
- Ensure that builds run on lowest supported major node version (v12)
- Don't run tests on centos 6
=> SNOW-847264: Always run tests on node v12 and drop centos6 test builds

ci/image/Dockerfile.nodejs-centos7-node14-build, ci/image/Dockerfile.nodejs-centos7-node14-test
Add centos7 with the latest node 14 docker images for build and test (they are equal for the internal CI process needs)
=> SNOW-875973: Prepare nodejs centos7 node14 docker image

lib/file_transfer_agent/azure_util.js, test/integration/testPutGet.js
`resolve` should be called as callback when finishing reading file from Azure Blob Storage. Without that received stream was often empty and we receive error:
```
1) PUT GET test multiple files
testUploadMultifiles:
Uncaught Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
at Decipheriv.final (internal/crypto/cipher.js:172:29)
at ReadStream.<anonymous> (D:\a\snowflake-connector-nodejs\snowflake-connector-nodejs\lib\file_transfer_agent\encrypt_util.js:272:32)
at ReadStream.emit (events.js:314:20)
at ReadStream.EventEmitter.emit (domain.js:483:12)
at internal/fs/streams.js:247:14
at FSReqCallback.oncomplete (fs.js:156:23)
```
=> SNOW-872497: Fix windows + azure problem when getting files from stage

.github/workflows/build-test.yml
CodeCov github action should be more stable with token and don't fail on Github limits
=> SNOW-886505: Add CodeCov token to github action

package.json
- Bump urllib 2.x minor version
- remove vm2 exclusion (since it is not required transitive dependency of urllib@2 anymore)
=> SNOW-890305: Bump minor urllib and delete vm2 exclusion

lib/logger/core.js
This is a long-standing behaviour which always bothered me :) How [moment's formatting is used for the logging](https://momentjs.com/docs/#/parsing/string-format/), is currently concatenating the minute+seconds in the millisecond position, instead of actually logging the millisecond. Probably a typo which was unfixed for such a long time.
The impact however is making the various issues a bit harder to debug, not having access to the sub-second timings.
Before the fix:
```
{"level":"DEBUG","message":"[7:58:49.5849 AM]: Reading OCSP cache file. /root/.cache/snowflake/ocsp_response_cache.json"}
{"level":"TRACE","message":"[7:58:49.5849 AM]: Returning OCSP status for certificate 05877196EF01E4B545435944CEEC71CD from cache"}
{"level":"TRACE","message":"[7:58:49.5849 AM]: Returning OCSP status …
```
=> fix millisec logging

lib/file_transfer_agent/file_transfer_agent.js, lib/file_transfer_agent/s3_util.js, package.json, test/unit/file_transfer_agent/s3_test.js
aws-sdk v2 causes warning message:
```
(node:39752) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```
and we should switch to AWS SDK in version 3.
**AWS SDK v3 needs Node version `>=14`**
=> SNOW-749232: Upgrade to aws-sdk v3

lib/global_config.js
Set new Function as default json parser
=> SNOW-811103: Set new Function as default json parser

.npmignore, samples/README.md, samples/helpers.js, samples/jsonParserComparison.js, samples/package.json
=> SNOW-811103 script to testing json parsers

.eslintrc.js, lib/queryContextCache.js, test/integration/testHTAP.js
=> SNOW-920977: Add space formatting rules to eslint configuration

test/integration/testHTAP.js, test/integration/testUtil.js
=> Query Context Cache integration testing fix

lib/http/base.js, package.json
=> SNOW-917244: Remove axios content encoding workaround

samples/README.md, samples/helpers.js, samples/package.json, samples/rowsVsStreamingQuery.js
=> SNOW-928823: Add rows vs streaming sample

.github/workflows/build-test.yml, ci/test_mac.sh, ci/test_ubuntu.sh, test/integration/testProxyExecute.js
=> SNOW-896752 - Add node20 on Ubuntu to github action tests

lib/authentication/auth_web.js, lib/authentication/authentication.js, lib/authentication/sso_url_provider.js, lib/connection/connection.js, lib/connection/connection_context.js, lib/http/base.js, lib/http/node.js, lib/services/sso_url_provider.js, test/integration/ocsp_mock/https_ocsp_mock_agent.js, test/integration/ocsp_mock/testConnectionOcspMock.js, test/unit/authentication/authentication_test.js
=> SNOW-334890: External browser SSO authentication with proxy

test/integration/testConnectionPoolExecute.js, test/integration/testLargeResultSet.js, test/integration/testPutGet.js, test/integration/testPutSmallFiles.js, test/integration/testUtil.js
=> SNOW-930831: Add randomization to the table name in put/get test

.github/workflows/jira_comment.yml
To prevent codecov[bot] spamming on Jira tickets we want to exclude it from comment action.
=> SNOW-859636 Exclude codecov[bot] from Jira Issue comments

lib/connection/result/column.js, package.json
Replaced the deprecated `floor` function in new versions of bignumber.js (>= 6.0) with the updated solution of calling `.integerValue(BigNumber.ROUND_FLOOR)`
=> SNOW-922989 Replace deprecated bignumber.js floor function

lib/services/sf.js
Regarding issue 678
The PR checks if a connection is renewing/connecting to determine if it is valid. This can prevent an `Already connected` error or `Connection already in progress` error which happens when a user calls the `isUp` or `isValidAsync` function and it returns false and the user then tries to connect manually while the connection is already renewing/connecting
=> SNOW-926029: Check for renewing/connecting state when validating a connection

lib/configuration/client_configuration.js
Prevent to fail if client config file could not be found because of an unexpected error during the phase of searching in predefined directory. It could happen if for example there is no home folder in the operating system.
=> SNOW-856233 easy logging - not fail on directory search error

lib/services/sf.js, lib/util.js, test/unit/util_test.js
=> Fix token-request in retry strategy.

lib/agent/https_proxy_ocsp_agent.js, lib/http/node.js, lib/services/sf.js, lib/util.js, test/unit/util_test.js
- generic observability: instead of swallowing the underlying error upon connectivity issue and emit a hard-to-debug generic error message, log that underlying error stack on DEBUG loglevel
- proxy: detecting if HTTP_PROXY/HTTPS_PROXY environmental variable is set, log them on DEBUG loglevel
- proxy: added logging for Connection's proxyPort and proxyUser (if set), had only proxyHost. 
-- this bit of logging now moved to generic agent
- proxy: if both HTTPS_PROXY and proxyHost is set, can lead to not-so-trivial-to-debug situations ; log this on WARN loglevel for more intuitive troubleshooting
=> SNOW-926008 supportability/observability enhancement for generic and proxy use-cases

lib/services/large_result_set.js
* extra logging for errors and unsuccessful responses in requests when retrieving query result from cloud storage
* '2515 milliseconds' is enough precision in the logs for retries (was: '2515.1356764370476 milliseconds')
=> SNOW-926008 observability improvements continued

lib/file_transfer_agent/azure_util.js, lib/file_transfer_agent/file_transfer_agent.js, lib/file_transfer_agent/local_util.js, lib/file_transfer_agent/remote_storage_util.js, lib/file_transfer_agent/s3_util.js, test/unit/file_transfer_agent/azure_test.js, test/unit/file_transfer_agent/s3_test.js
This change reuses the storage clients created in file_transfer_agent.js and destroys them when no longer needed to avoid increasing memory usage in the S3 use case (fixes #734 ).
=> Reuse storage clients + destroy when no longer needed (fixes #734)

package.json
bump `axios` to 1.6.5
to address High (7.5) severity vulnerability with prototype pollution which is fixed in `axios` 1.6.4
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788
=> SNOW-1001672 bump `axios` to 1.6.5

lib/file_transfer_agent/azure_util.js, lib/file_transfer_agent/file_transfer_agent.js, lib/file_transfer_agent/local_util.js, lib/file_transfer_agent/remote_storage_util.js, lib/file_transfer_agent/s3_util.js, test/unit/file_transfer_agent/azure_test.js, test/unit/file_transfer_agent/s3_test.js
=> Revert commit of reuse storage clients

package.json
SNOW-1031704 - checked first as a Draft and all test seem to pass. So converting to a regular one.
Besides upgrading to the newer version of the dependency, this PR also aims to address the concern caused by v6 of the dependency, leading to issues in Next.js 
```
./node_modules/@google-cloud/storage/node_modules/retry-request/index.js
Module not found: Can't resolve 'request' in '/path/to/node_modules/@google-cloud/storage/node_modules/retry-request'
```
see https://github.com/snowflakedb/snowflake-connector-nodejs/issues/759
=> SNOW-1031704 bump `@google-cloud/storage` to v7

lib/configuration/client_configuration.js, lib/logger/easy_logging_starter.js, lib/util.js, test/unit/configuration/configuration_finding_test.js, test/unit/logger/easy_logging_starter_test.js
Fix driver directory determination in Easy Logging
=> SNOW-1016523 fix driver directory determination in Easy Logging

lib/connection/result/sf_timestamp.js, test/unit/connection/result/result_test_timestamp.js
There were specific timestamps that were displayed incorrectly.
In Snowsight (the data is correct):
Using the Node Connector (look specifically at the "TO JSON" log):
When a SfTimestamp is created, it receives a number of epochSeconds and a number of incremental nanoSeconds. The SfTimestamp object has a property for the nanoseconds and a **moment** property.
The number of milliseconds was sometimes rounded up (from 253402300799999.999999 to 253402300800000, for example), but the property nanoseconds was not changed accordingly to reflect this rounding. This meant that, if we had 253402300799999.999999 epoch milliseconds, that would create a SfTimestamp with a moment that represents 253402300800000 epoch milliseconds, and with a nanosecond property of 999999999. That is actually …
=> SNOW-1230848 Fix timestamp discrepancy related to rounding issue in sf_timestamp

package.json
The fix for the CVE is already available with `follow-redirects` 1.15.6 which is installed with `axios` 1.6.8 Snyk URL: https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6444610
Current requirement for `^1.6.5` already allows for `axios` 1.6.8 to be automatically installed upon every (re)installation of `snowflake-sdk` but still better to bump the minimum version
=> SNOW-1281470 bump axios to 1.6.8 to address CVE-2024-28849

lib/authentication/auth_web.js, test/unit/authentication/authentication_test.js
Starting with Chrome v123 the browser sends the `OPTIONS` request first, instead of `GET` thus the `externalbrowser` auth was failing.
=> SNOW-1278568: Fix externalbrowser auth for Chrome browser

lib/connection/result/sf_timestamp.js
@sfc-gh-pmotacki mentioned to me that the [fix ](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/799) for SNOW-1230848 has resulted in a degraded performance when fetching rows that include timestamps. This change keeps the same fix but, instead of "parsing" the epoch seconds and nano seconds, it assigns them directly to the Moment.
=> [SNOW-1230848] Modify the way in which the Moment is created

lib/connection/result/sf_timestamp.js, test/unit/connection/result/result_test_timestamp.js
Previously, some changes had been done to address the bug SNOW-1230848. However, these changes resulted in a loss of precision in some cases in which milliseconds were used. After thinking more about this, the solution I propose is the following: instead of the original `Moment((epochSeconds * 1000) +(nanoSeconds / 1000000))`, we can use `Moment((epochSeconds * 1000) + Math.trunc(nanoSeconds / 1000000))`. This prevents the bug SNOW-1230848 (which was caused by rounding, and is described in detail [here](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/799), while also preserving milliseconds and nanoseconds precision (some unit tests were added to validate this).
=> SNOW-1230848: Fix error related to milliseconds precision

lib/file_transfer_agent/file_transfer_agent.js, package.json
1. Used `path.basename` in a place where a slash was used to obtain the name of a file from a path (the slash does not work well in Windows)
2. Updated glob from v9 to v10
In `file_transfer_agent.js`, there was a place where a slash was used as the path separator (instead of the more general `path.sep`, or using `path.basename` directly). This caused the files uploaded (from Windows) with PUT to be uploaded with their absolute path instead of the corresponding relative path (see screenshot below).
I updated **glob** from `^9.0.0` to `^10.0.0`. With v9, there was a problem that caused `glob.sync` to not find some paths in Windows (particularly in a Windows virtual machine running on Parallels. I actually believe this is working well in the Windows machines that are used to run tests with …
=> Fix errors that happen on Windows when using PUT command

lib/authentication/auth_okta.js, lib/connection/connection_config.js, lib/constants/error_messages.js, test/unit/connection/connection_config_test.js, test/unit/mock/mock_test_util.js
=> SNOW-1226630 Parameter to disable SAML URL check for Node.js driver(2)

index.d.ts
Adds `clientConfigFile` to `ConnectionOptions` type as per [documented](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-options#additional-connection-options) additional connection options
Closes #842
=> Add clientConfigFile to ConnectionOptions type 

lib/authentication/auth_keypair.js, lib/authentication/authentication.js, lib/services/sf.js, test/unit/authentication/authentication_test.js, test/unit/mock/mock_test_util.js
=> SNOW-1369242 - In node.js driver jwt token is not recreated for each login endpoint call

lib/file_transfer_agent/encrypt_util.js, test/unit/file_transfer_agent/encrypt_util_test.js
Add support for AES 256 encryption, so that PUT/GET statements work when the account parameter `CLIENT_ENCRYPTION_KEY_SIZE` is set to 256 (currently, an error is thrown and the files are not uploaded/downloaded). This is achieved by:
1. Making sure the file key has the appropriate size.
2. Passing the corresponding string to the `crypto` methods (`aes-128-cbc`, `aes-256-cbc`, `aes-128-ecb` or `aes-256-ecb`, depending on the case).
[APPS-42445]: https://snowflakecomputing.atlassian.net/browse/APPS-42445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [APPS-42445] Support AES 256 encryption/decryption

index.d.ts, lib/connection/connection_config.js, package.json
=> SNOW-1454926 statement.cancel isn't available anymore with Typescript (v1.11.0 regression) - missing types

index.d.ts
The type is a little off. JSON.stringify returns a string, not a String.
This causes a linting error for clients. 
I'm guessing since this repo uses all of the interfaces instead of the primitives for the JSDocs, string was typo'd as String in the types file.
=> Types: Serialized connection is a lowercase string from JSON.stringify, not the nonstandard String 

lib/configuration/client_configuration.js, lib/configuration/connection_configuration.js
Implemented logging for configuration layer.
=> Snow 1634717 configuration layer

lib/connection/connection.js
Closes: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/907
Pass the `callback` to `heartbeat` method.
This bug was introduced in https://github.com/snowflakedb/snowflake-connector-nodejs/pull/502
Traces:
```
[7:44:10.457 AM]: Failed to all retries to SF.
"[7:44:10.456 AM]: Encountered an error when sending the request. Details: {""code"":""ERR_INVALID_ARG_TYPE""}"
[7:44:10.319 AM]: CALL POST with timeout 90000: https://<redacted>.snowflakecomputing.com/session/v1/login-request?requestId=e80920bc-856b-4c35-aa16-97c5d90d36cd&warehouse=<redacted>&databaseName=<redacted>&schemaName=<redacted>&clientStartTime=1726213252067&retryCount=6
[7:44:10.318 AM]: Get agent with id: https://<redacted>.snowflakecomputing.com-keepAlive from cache …
```
=> SNOW-1658878: pass callback to heartbeat call

index.d.ts
I believe it was missed. It's declared in the documentation and used in the source code.
Thanks
=> fix(typings): Missing declaration for OFF as LogLevel

index.d.ts, lib/connection/connection.js, lib/services/sf.js, test/integration/testManualConnection.js
=> SNOW-1694143: Fix sso token authentication

index.d.ts
The type definition for `Connection` was missing `getServiceName()`
=> Add missing `Connection.getServiceName` type definition

lib/http/node.js, lib/util.js, test/unit/agent_cache_test.js
=> SNOW-1346341 adding destination to httpsAgent cache key to be able to apply separate settings for separate destinations

lib/core.js
In https://github.com/snowflakedb/snowflake-connector-nodejs/issues/957 is was reported that even with
`snowflake.configure({ logLevel: OFF });`
which is expected to disable logging; a single logline is still logged
```
{"level":"INFO","message":"[2:27:54.321 PM]: Configuring logger with level: -1, filePath: undefined, additionalLogToConsole: undefined"}
```
at default `INFO` level before setting loglevel to `-1` and actually disabling logging. 
Moving this logline to after the logger has been configured with local loglevel allows for preserve the same information for the ones who need it for tracking purposes, and stop logging it for the ones who wish the driver to not emit logs.
=> SNOW-1800528 don't log anything if logLevel is set to `OFF`

lib/util.js, test/unit/util_test.js
=> SNOW-1825719 - setting proxy port if default was skipped during parsing

.github/PULL_REQUEST_TEMPLATE.md
Added to PR checklist point: "Extend the types in index.d.ts file (if necessary)
=> Added point about types to PR checklist

lib/file_transfer_agent/azure_util.js, test/integration/testExecute.js, test/integration/testUtil.js
Node.js - Testing resubmitting requests using request id
=> SNOW-1843504 - Testing resubmitting requests using request id

README.md, package.json
=> Bumped up the NodeJS Driver MAJOR version from 1.15.0 to 2.0.0

.github/workflows/build-test.yml, ci/container/test_component.sh, ci/test_windows.bat, test/unit/authentication/json_credential_manager_test.js
[SNOW-952788](https://snowflakecomputing.atlassian.net/browse/SNOW-952788)
[SNOW-952788]: https://snowflakecomputing.atlassian.net/browse/SNOW-952788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-952788 remove support for node 14 and 16

lib/file_transfer_agent/gcs_util.js, lib/util.js, test/unit/file_transfer_agent/gcs_test.js, test/unit/util_test.js
=> SNOW-1789759: NodeJS Support GCS region specific endpoint (Axios)

package.json
* `@aws-sdk/client-s3` - the current dependency specification anyways installs latest `3.726.0` already, but since already changing package.json, i figured I can note this too
* `@smithy/node-http-handler` - we currently install latest v3 , `3.3.3`. They released a new major version because they dropped support for node:16 (reference: https://github.com/smithy-lang/smithy-typescript/releases/tag/%40smithy%2Fnode-http-handler%404.0.0) and we already dropped support for node:16 in snowflake-sdk earlier.
=> SNOW-1878222 bump node-http-handler to next major, v4

README.md
=> SNOW-1895435- Expand the documentation - signing verification

lib/authentication/auth_idtoken.js, lib/authentication/authentication.js, lib/connection/connection_config.js, test/unit/authentication/authentication_test.js
We've been patching this for 1.5 years on our end. Without it, there are SSO problems when customers login, since the VS Code API has an API to openExternal: https://code.visualstudio.com/api/references/vscode-api (search for openExternal) that controls how browser windows open from extensions. 
Can we have this officially inside the node connector? 
=> [APPS-45767] Let an external browser callback be provided to use, supports Snowflake VS Code Extension SSO

system_test/connectionOptions.js
SNOW-1935764: on jenkins tests account name may be set to different than host parameter - let's read the value from host parameter then
=> SNOW-1935764: Fix account value in jenkins tests

lib/agent/check.js, lib/agent/ocsp_response_cache.js
node 22 with `--track-deprecation` complains that
```
[2025-04-10T09:38:57.600Z] (node:292) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
at OcspResponseCache.downloadCache (/test/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js:269:26)
at getOcspCache (/test/node_modules/snowflake-sdk/lib/agent/socket_util.js:238:35)
at /test/node_modules/snowflake-sdk/lib/agent/socket_util.js:297:11
at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
```
Per https://nodejs.org/docs/latest-v22.x/api/util.html#util_extendtarget-source, `Object.assign` should be used; which has the same input arguments as deprecated `util._extend`
=> SNOW-2034298 replacing deprecated util._extend with Object.assign

lib/file_transfer_agent/gcs_util.js, test/unit/file_transfer_agent/gcs_test.js
=> SNOW-2032701 NodeJS driver support virtual-style domains(3)

lib/core.js, test/unit/snowflake_test.js
Fixes a inconsistency where `ErrorCode` was defined in d.ts file but not exported at runtime, causing runtime errors despite TypeScript compilation success.
- Added `ErrorCode: ErrorCodes` property to the core module instance
- Error codes are now accessible via `snowflake.ErrorCode` at runtime
- TypeScript definitions already included the enum, now matching the JavaScript implementation
=> SNOW-2129006: Add ErrorCode to core instance.

index.d.ts, lib/authentication/auth_workload_identity/auth_workload_identity.ts, lib/connection/connection_config.js, lib/connection/types.ts, test/unit/authentication/auth_workload_identity/auth_workload_identity_test.ts, test/unit/authentication/authentication_test.js
1. feature flag in evn variable instead of ConnectionOptions to be consistent with other drivers
2. `workloadIdentity` object replaced with 2 separate keys because .toml config don't support nested fields
=> SNOW-1902245 Fix workload identity config options

lib/file_transfer_agent/gcs_util.js, lib/util.ts, test/unit/file_transfer_agent/gcs_test.js, test/unit/util_test.js
This PR is identical to https://github.com/snowflakedb/snowflake-connector-nodejs/pull/1119 but with removal of unneeded `.nextTick`
https://snowflakecomputing.atlassian.net/browse/SNOW-2198697
https://github.com/snowflakedb/snowflake-connector-nodejs/pull/1059 introduced handling for the `useVirtualUrl` but the implementation is incomplete.
The problem is that virtual domains are now used with the Json API which doesn’t support virtual-style domains. The issue is that the virtual-style domains are used with the GCP client [snowflake-connector-nodejs/lib/file_transfer_agent/gcs_util.js at master · snowflakedb/snowflake-connector-nodejs](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/file_transfer_agent/gcs_util.js#L293-L305) , so the full URL is like …
=> SNOW-2198697 Use GCP XML API when useVirtualUrl=true

index.d.ts, lib/agent/crl_utils.ts, lib/agent/crl_validator.ts, lib/connection/connection_config.js, lib/connection/types.ts, lib/core.js, lib/global_config_typed.ts, test/unit/agent/crl_validator_test.ts, test/unit/global_config.ts
Related to CRL caching implemented in pending PR https://github.com/snowflakedb/snowflake-connector-nodejs/pull/1163
* Moved some config options to the global config
* created new GlobalConfig with TypeScript 
* added a NOTE with migration plan
Developers are reading our source code, and it's very difficult for them to understand what's going on in our config. There are 5000+ lines of config-related code with undocumented defaults, undocumented env variables, mistakes in value validators, and inconsistent error codes. All of this can be reduced to ~500 lines of code with Typescript + default values map.
Other popular SDKs don't do param validation either and rely on defaults, TS, and runtime errors.
=> SNOW-2117146 Move some CRL options to GlobalConfig

CHANGELOG.md, index.d.ts
Addresses #1093 
Since we check if the bind variables' array is JSON.stringifiable ([ref](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/v2.2.0/lib/connection/statement.js#L363-L369)) and doesn't return `undefined`, in principle then the typing should also reflect it and list the objects which are supposed to be correctly stringifiable (have `toJSON()` method) 
We already had a complaint about this, see above Issue. So extending the Bind typing accordingly.
=> SNOW-2143625 add boolean and null to Bind typing

.github/CODEOWNERS
Add pki-oversight as a joint owner for PKI-related files. Similar to https://github.com/snowflakedb/gosnowflake/pull/1581
=> SNOW-2306340: Add pki-oversight as a joint owner for PKI-related files
