snowflakedb/snowflake-connector-nodejs

- .npmignore
- README.rst
Update the build and test badge.
Codecov will be added in the separate JIRA.
> Snow 80116 add badge

- lib/services/large_result_set.js
SNOW-143538 Retry connection for ETIMEOUT tcp error.
> Workaround for SNOW-143538

- lib/services/large_result_set.js
Co-authored-by: Michał Wadas <michalwadas@gmail.com>
This attempts to mitigate #85
> prep-1.5.2

- ci/container/test_component.sh
- ci/image/Dockerfile.nodejs-centos6-default-dev
- ci/test.sh
- package.json
- clean up ci scripts.
- deleted dev container
> Snow 155635 cleanup

- .github/workflows/build-test.yml
- .gitignore
- ci/_init.sh
- ci/build.sh
- ci/container/build_component.sh
- ci/container/wss.sh
- ci/image/Dockerfile.nodejs-centos6-default-build
- ci/image/Dockerfile.nodejs-centos6-default-test
- ci/image/Dockerfile.nodejs-centos7-node12-test
- ci/image/scripts/git.sh
- scripts/wss.sh
Add WhiteSource scan script to NodeJS driver.
> SNOW-160668 add wss to NodeJS Driver

- ci/build.sh
- ci/container/wss.sh
- ci/test.sh
This fixes the WSS for master branch.
> fixed master

- ci/container/test_component.sh
- system_test/testLongQuery.js
Fix flaky test testPingPong::testLongRunning by increasing timeout to 120s
> SNOW-180324 Fix flaky test testPingPong::testLongRunning

- Jenkinsfile
https://ci44.int.snowflakecomputing.com/view/GithubFolders/job/NodeJS/job/snowflake-connector-nodejs/view/change-requests/job/PR-128/  This is where the PR's will be linked
> SNOW-166174 Add Jenkinsfile for NodeJS PR Builder

- .github/workflows/build-test.yml
- ci/container/test_component.sh
- ci/test_mac.sh
Increased test timeout and added shorter OCSP timeout for unresponsive OCSP responders as suggested in OCSP cache issue ticket
> SNOW-225131: Increased test timeout and added shorter OCSP timeout

- package.json
> SNOW-294006: Bumped up the NodeJS Driver MINOR version from 1.5.3 to 1.6.0

- lib/authentication/auth_web.js
- lib/authentication/authentication.js
- lib/connection/connection_config.js
- test/unit/authentication/authentication_test.js
Set the host variable in the connection config to prevent part of its value being omitted
> Add host variable to connection config

- lib/agent/check.js
- lib/connection/connection.js
- test/integration/connectionOptions.js
- test/integration/testOcsp.js
Use privatelink for OCSP URL when the specified account is using privatelink.
> Check for privatelink and set as OCSP url if it exists

- package.json
> Update agent-base to 4.3.0

- lib/connection/connection.js
- lib/core.js
- package.json
- test/integration/testConnection.js
> Add connection pool capability to connector

- lib/authentication/authentication.js
- lib/connection/connection.js
- lib/connection/connection_config.js
- lib/services/sf.js
- test/unit/authentication/authentication_test.js
- test/unit/connection/connection_config_test.js
> Add 'application' connection parameter

- package.json
> SNOW-458983: Bumped up the NodeJS Driver PATCH version from 1.6.2 to 1.6.3

- package.json
> SNOW-480572: Bumped up the NodeJS Driver PATCH version from 1.6.3 to 1.6.4

- package.json
> Upgrade axios to 0.21.4

- .github/workflows/jira_comment.yml
- .github/workflows/jira_issue.yml
Committed via https://github.com/asottile/all-repos
> SNOW-499170 Bringing GH actions up-to-date with Python connector's

- package.json
Update Mocha Version to 9.2.0 
@sfc-gh-jlin @sfc-gh-abhatnagar
> Update Mocha Version to 9.2.0

- package.json
Relates to https://github.com/advisories/GHSA-pw2r-vq6v-hr8c
> Update followRedirect to v1.14.8

- lib/authentication/auth_web.js
- package.json
> Display success page on browser when connection is authenticated

- package.json
Based on https://github.com/snowflakedb/snowflake-connector-nodejs/pull/241
> Update agent-base and https-proxy-agent

- lib/connection/result/result.js
- lib/util.js
Based on https://github.com/snowflakedb/snowflake-connector-nodejs/issues/165
> Initialize variables to prevent global leak

- package.json
> Update 'qs' to 6.10.3

- lib/connection/connection_config.js
> Add 'application' to default parameters list

- package.json
> Update 'axios' to 0.27.2

- lib/connection/connection_config.js
Based on SF# 00382081
The previous PR only fixed the issue for accounts without a region. This addresses the issue for accounts with a region
> Set region value in connection config

- lib/agent/https_ocsp_agent.js
- lib/agent/https_proxy_ocsp_agent.js
- lib/connection/connection_config.js
- lib/http/base.js
- lib/http/node.js
- package.json
- test/integration/ocsp_mock/https_ocsp_mock_agent.js
> Replace deprecated request package

- lib/http/base.js
> Set default timeout to 360 seconds

- test/unit/util_test.js
> Add unit test for isRetryableHttpError() function

- .github/workflows/build-test.yml
Run node github action tests in sequence
> Run github action tests sequentially

- package.json
Update moment dependency to 2.29.4
> Update moment to 2.29.4

- .github/workflows/semgrep.yml
- Jenkinsfile
SNOW-667402:Security Update. 
This PR creates/updates the Semgrep static analysis workflow. Local semgrep rules have been deleted. If your repo had a semgrep stage in the Jenkinsfile, we attempted to delete it. Please review changes and merge them as soon as possible.
[Announcement](https://snowflake.slack.com/archives/C02BTC3HY/p1661797484408489)
> SNOW-667402:Semgrep workflow update

- .github/workflows/build-test.yml
Prioritize running the required checks first before the non-required ones
> Run required tests first on github actions

- README.md
Regarding issue 114
Add information to the README to run mocha and get the code coverage results manually
> Update README with steps to retrieve code coverage manually

- lib/authentication/auth_web.js
- lib/url_util.js
- test/unit/authentication/authentication_test.js
- test/unit/url_util_test.js
Validate SSO URL to prevent command execution for attacker-controlled connection strings.  Also added URL Encoder to encode base64 strings to url safe format.
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/266
> SNOW-761012 Added URL Validator and URL Encoder

- lib/secret_detector.js
Regarding isssue 338
Running tests for PR https://github.com/snowflakedb/snowflake-connector-nodejs/pull/461
> Fix the error for the maskedtxt variable not being defined

- package.json
> SNOW-824349_nodejs_version_bump

- .github/PULL_REQUEST_TEMPLATE.md
> SNOW-829175: Add PR issue template

- .pre-commit-config.yaml
- ci/container/package.json
- package.json
Some of dependencies are needed only for test. Better place for them is the devDependencies section in package.json
> Move test dependencies to devDependencies section

- test/integration/testArrayBind.js
- test/integration/testArrayBindCustomerTable.js
- test/integration/testUtil.js
Fix 2 regression tests that fail in internal build.
> SNOW-830232: Fix regression tests

- .github/workflows/cla_bot.yml
> SNOW-829489: Fix CLA Bot

- lib/authentication/auth_default.js
- lib/authentication/auth_keypair.js
- lib/authentication/auth_oauth.js
- test/unit/authentication/authentication_test.js
> SNOW-831628: Ensure all authenticate methods are thenable

- lib/connection/connection.js
Catch `heartbeat` errors and return `false` then from `connection.isValidAsync`
> SNOW-358605: Make isValidAsync always resolve

- lib/constants/error_messages.js
Issue [215](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/215)
> Add to error message that fetchAsString accepts Buffer.

- package.json
> SNOW-837553_nodejs_version_bump

- lib/connection/connection.js
- test/integration/testConnection.js
> SNOW-358605: Let heartbeatAsync return the same result as with select 1

- package.json
> remove qs from devDependencies as it seems to be unused

- lib/connection/connection_config.js
- test/unit/connection/connection_config_test.js
Issue [464](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/464)
> Update OAUTH connection options and username is no longer required.

- README.md
- scripts/format_code.sh
- webstorm-codestyle.xml
- Change webstorm configuration to match the eslint config
- Remove script to run webstorm formatter
- Remove info about running formatting via webstorm from Readme
> SNOW-829190: Update webstorm config

- .github/workflows/audit.yml
- ci/container/build_component.sh
- package.json
> SNOW-841052: Don't block build on npm audit

- test/integration/testArrayBind.js
Retry test array bind with cancel flaky test
> SNOW-831683: Retry test array bind cancel test

- .github/workflows/build-test.yml
- .gitignore
- README.md
- ci/container/package.json
- ci/container/test_component.sh
- ci/test_mac.sh
- package.json
Configure nyc - code coverage library and corresponding steps in jenkins steps
> SNOW-830950: Configuration of nyc - code coverage library

- package.json
> Upgrade word-wrap for snyk issue

- .github/workflows/cla_bot.yml
Add `snyk-bot` user to CLA Assistant allowlist
> SNOW-870818: Add snyk-bot to CLA Assistant allowlist

- .github/workflows/build-test.yml
- README.md
- ci/container/test_component.sh
- report code coverage in lcov format next to text
- add codecov uploader of gathered code coverage with nyc
- add codecov badge
> SNOW-870360: Integrate with code cov

- .github/workflows/build-test.yml
Add checkout action to upload code coverage job
> SNOW-870360: Fix code cov upload

- Jenkinsfile
> Update Jenkinsfile back to centos6 to unblock BPTP

- .github/workflows/build-test.yml
- ci/container/test_component.sh
Reverts snowflakedb/snowflake-connector-nodejs#573
> Revert "SNOW-847264: Always run tests on node v12 and drop centos6 test builds"

- package.json
Exclude vulnerable vm2 transitive dependency
> SNOW-865533: Exclude vulnerable vm2 transitive dependency

- README.md
> SNOW-880333: Fix installation instruction

- .github/workflows/build-test.yml
> SNOW-880391: Do not cancel other matrix builds when one fails

- .github/workflows/build-test.yml
- Jenkinsfile
- ci/_init.sh
> SNOW-847264: Use centos7 with node14 image

- .npmignore
There are some files in the repository that are included in distributed package but they are only necessary during development
> SNOW-891296: Exclude development files from distributed package

- .github/workflows/build-test.yml
- ci/container/test_component.sh
Simplify github workflows to run tests on each cloud provider (AWS, AZURE, GCP), operating system (Centos, Mac, Windows), main supported node version (14.x, 16.x, 18.x - but Centos only with node 14.x).
Code coverage is aggregated from all Mac builds
> SNOW-879602: Simplify github workflows

- test/unit/file_transfer_agent/azure_test.js
- test/unit/file_transfer_agent/gcs_test.js
- test/unit/file_transfer_agent/s3_test.js
> [SNOW-892547] Remove references to sfcdev1 buckets

- lib/connection/result/result.js
- test/integration/testLargeResultSet.js
Add test for specific chunk download performance problem
> SNOW-743920: Add test fetching many chunks

- package.json
> SNOW-896989: Bumped up the NodeJS Driver MINOR version from 1.7.0 to 1.8.0

- package.json
Update uuid package version to v8.
> SNOW-896729: Update uuid to version 8

- lib/http/base.js
Add todo comment for gcp response customization on GZIP
> SNOW-896805: Add todo comment for gcp response customization on GZIP

- package.json
> SNOW-921833: Bumped up the NodeJS Driver MINOR version from 1.8.0 to 1.9.0

- lib/connection/connection_config.js
- package.json
- test/integration/testConnection.js
> SNOW-913627: Replace string-similarity with fastest-levenshtein

- test/integration/testConnectionWithOCSP.js
> SNOW-929946: Refactor connection with OCSP tests

- test/integration/ocsp_mock/testConnectionOcspMock.js
> SNOW-334890 - fix tests running

- test/integration/ocsp_mock/testConnectionOcspMock.js
> SNOW-949387: Remove unnecessary logging

- ci/container/package.json
- ci/container/test_component.sh
- package.json
Update the mocha version to the newest one in the package and CI.
> SNOW-914688: Update mocha version

- lib/authentication/auth_okta.js
- test/unit/authentication/authentication_test.js
Fix response handling in auth_okta as the axios v.1.6.0 returns it differently than previous one.
> SNOW-964608: Fix response handling for auth_okta

- package.json
> SNOW-968872: Bumped up the NodeJS Driver PATCH version from 1.9.0 to 1.9.1

- .github/workflows/build-test.yml
Sync the MacOS clock before running the tests.
> SNOW-982481: Sync MacOS time

- lib/agent/https_proxy_ocsp_agent.js
- lib/connection/connection_config.js
- package.json
- system_test/connectionOptions.js
> Test pr 679

- package.json
> PATCH: Bumped up the NodeJS Driver PATCH version from 1.9.1 to 1.9.2

- .pre-commit-config.yaml
Use drivers pre-commit hook to ignore secret-detector tests.
> SNOW-984450: Use drivers pre-commit hook

- lib/connection/statement.js
> SNOW-988855: Remove outdated default comment

- lib/connection/connection_config.js
- test/unit/connection/connection_config_test.js
As a parity with other drivers, add a host parameter which can be used to set the snowflake host.
> SNOW-993553: Add host parameter

- package.json
This reverts commit 09fbdc6a5c04eaeb1b2632363ef82cddfd38c4c0.
> Revert "Bumped MINOR driver version from 1.9.2 to 1.9.3 (#750)"

- lib/configuration/client_configuration.js
- lib/connection/connection.js
- lib/logger/core.js
- lib/logger/easy_logging_starter.js
- lib/logger/node.js
- lib/util.js
- test/configureLogger.js
- test/integration/testConnection.js
- test/integration/testEasyLoggingOnConnecting.js
- test/unit/configuration/configuration_finding_test.js
- test/unit/configuration/configuration_parsing_test.js
- test/unit/logger/easy_logging_starter_test.js
- test/unit/util_test.js
> SNOW-1016523: Easy Logging fixes

- .github/workflows/jira_issue.yml
Update area in JIRA integration
> SNOW-1111018: Update area

- package.json
> MINOR: Bumped up the NodeJS Driver MINOR version from 1.9.3 to 1.10.0

- .github/workflows/jira_issue.yml
Update jira_issue.yml with owner per revised processes
> SNOW-1156105 Update jira_issue.yml with owner per revised processes

- .github/workflows/jira_issue.yml
SNOW-1156105 fix typo as components is plural (also an array)
> SNOW-1156105 fix typo as components is plural (also an array)

- lib/util.js
- test/unit/connection/connection_config_test.js
> SNOW-1234229- Fix validation for short account names

- lib/connection/bind_uploader.js
- test/integration/testArrayBind.js
> SNOW-1234335 fix data format in bulk upload csv file

- ci/container/test_component.sh
- ci/test_windows.bat
> node14 and @azure - force an older compatible version

- lib/connection/connection.js
> SNOW-1018408: Fix unhandled auth promise rejections in synchronous connect

- SECURITY.md
> SNOW-1293828 Update security policy

- package.json
> PATCH: Bumped up the NodeJS Driver PATCH version from 1.10.0 to 1.10.1

- .eslintrc.js
- samples/README.md
- samples/jsonParserComparison.js
- samples/rowsVsStreamingQuery.js
Cleanup samples folder to stop throwing warnings.
> SNOW-1300062: Cleanup samples

- .github/workflows/build-test.yml
> SNOW-1353732: Edit the mac OS setting in the github workflow.

- package.json
> MINOR: Bumped up the NodeJS Driver MINOR version from 1.10.1 to 1.11.0

- package.json
> Fix for azure-storage-blob for node14 users

- index.d.ts
trying to address https://github.com/snowflakedb/snowflake-connector-nodejs/issues/860
thanks to @etienne-collibra !
> SNOW-1508219 (types) `complete` is optional

- lib/configuration/connection_configuration.js
- test/unit/configuration/configuration_parsing_test.js
> SNOW-1514498 - fix user/username parameter key using file configuration 

- test/integration/testMaxLobSize.js
Add test for increased max lob size parameter switch
> SNOW-1163209: Add test for increased max lob size parameter switch

- lib/core.js
- test/integration/testManualConnection.js
> SNOW-1487602-connection-toml-using-pool

- lib/configuration/connection_configuration.js
- lib/connection/connection_config.js
- lib/core.js
- test/unit/configuration/configuration_parsing_test.js
> SNOW-1487602 User not obligatory for oauth authentication type

- test/integration/testMaxLobSize.js
Added test for stage scan & insert for values with size > 16MB (via "COPY INTO")
> SNOW-1522397 Add test for large values stage insert

- test/integration/testOcsp.js
On CI environment there is a problem with assertion of serwer response after OCSP confirmation. The assertion of expected error code had been changed.
> SNOW-1556044 ocsp tests fails

- ci/image/Dockerfile.nodejs-centos7-fips-test
- lib/configuration/connection_configuration.js
- lib/file_transfer_agent/file_util.js
- test/unit/configuration/configuration_parsing_test.js
Added file checksum value to logs about configuration files using to read connection parameters
> SNOW-1556044 - Logging checksum of configuration file

- .github/workflows/build-test.yml
- lib/file_transfer_agent/file_util.js
- test/integration/connectionOptions.js
- test/integration/testConnection.js
- test/unit/configuration/configuration_parsing_test.js
- test/unit/file_transfer_agent/file_util_test.js
SNOW-1332628:  Fix and test for permission verification
> SNOW-1332628: Fix and test for permission verification

- lib/util.js
- test/unit/connection/connection_config_test.js
> SNOW-1569214: Fix regex for account name validation

- package.json
> MINOR: Bumped up the NodeJS Driver MINOR version from 1.11.0 to 1.12.0

- lib/http/base.js
- test/integration/testConnection.js
Add Axios error & response sanitization
> SNOW-1623135: Add Axios error & response sanitization

- lib/http/base.js
- test/integration/testConnection.js
> SNOW-1623135: Refactor errors

- index.d.ts
Fixes the return types of async functions in connection. These methods return a Promise because they're async functions.
> fix return type of async functions

- package.json
> MINOR: Bumped up the NodeJS Driver MINOR version from 1.12.0 to 1.13.0

- package.json
> PATCH: Bumped up the NodeJS Driver PATCH version from 1.13.0 to 1.13.1

- package.json
> SNOW-1650062 verification of typings

- package.json
> MINOR: Bumped up the NodeJS Driver MINOR version from 1.13.1 to 1.14.0

- .github/workflows/build-test.yml
[SNOW-1356385](https://snowflakecomputing.atlassian.net/browse/SNOW-1356385) Added node 22 to test matrix 
[SNOW-1356385]: https://snowflakecomputing.atlassian.net/browse/SNOW-1356385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-1356385 add tests for node 22 to matrix

- lib/connection/statement.js
Snowflake NodeJs driver eslint rules application changed resultIds check from a loose to a strict value undefined check, which doesn't match null value.
> SNOW-1774162: Add null check for resultIds

- package.json
> MINOR: Bumped up the NodeJS Driver MINOR version from 1.14.0 to 1.15.0

- package.json
Upgrade axios to the newest version. Versions lower than 1.7.3 were affected by https://security.snyk.io/vuln/SNYK-JS-AXIOS-7361793
> SNOW-1621729. Bumped axios to version 1.7.7.

- .github/workflows/audit.yml
- .github/workflows/build-test.yml
- .github/workflows/jira_close.yml
- .github/workflows/jira_issue.yml
- .github/workflows/lint.yml
- .github/workflows/snyk-issue.yml
- .github/workflows/snyk-pr.yml
> SNOW-1825712: Update GH actions versions

- Jenkinsfile
[SNOW-1852300](https://snowflakecomputing.atlassian.net/browse/SNOW-1852300)
[SNOW-1852300]: https://snowflakecomputing.atlassian.net/browse/SNOW-1852300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-1852300 use bptp-built tag for nodejs tests

- lib/proxy_util.js
- test/unit/proxy_util_test.js
> SNOW-1825719-Proxy port is lost using default proxy port on Windows

- ci/image/proxy/Dockerfile
- ci/image/proxy/Dockerfile.auth
> SNOW-1678992: NodeJS driver has squid exposed user name and password in Dockerfile

- test/integration/testBind.js
>  SNOW-1313628: NodeJS - Verify value bindings for all field types while exceeding CLIENT_STAGE_ARRAY_BINDING_THRESHOLD

- package.json
- system_test/testProxy.js
- system_test/testSystemGetObjects.js
- system_test/testToken.js
> Bump version to 2.0.3

- ci/image/Dockerfile
> SNOW-1825478 - update Dockerfile

- lib/secret_detector.js
- test/unit/secret_detector_test.js
Added extension to control masking logs containing OAuth sensitive parameters.
> SNOW-1825499 - secret detector extensions for oauth parameters

- test/integration/testBind.js
> SNOW-1982168 fix binding tests

- system_test/testLongQuery.js
- system_test/testSystemSetWhSnowflakeSupportFlag.js
Disable tests that are not related to driver functionalities.
> NO-SNOW: Disable system tests

- lib/agent/ocsp_response_cache.js
> SNOW-2028060: Fix OCSP response cache entries not being refreshed

- lib/authentication/auth_oauth_authorization_code.js
- lib/authentication/authentication_util.js
- lib/util.js
- test/integration/wiremock/testOauthAuthorizationCode.js
> Added a verification of redirect port availability

- package.json
> NO-SNOW: Bump version to 2.0.4

- lib/util.js
- test/unit/util_test.js
SNOW-2095188: Fix RegExp responsible for smkId string conversion
> SNOW-2095188: Fix RegExp responsible for smkId string conversion

- lib/authentication/auth_oauth_authorization_code.js
- lib/authentication/auth_oauth_client_credentials.js
- lib/authentication/authentication_util.js
- lib/connection/connection_config.js
- lib/util.js
- test/integration/wiremock/testOauthRefreshToken.js
- test/unit/connection/connection_config_test.js
> SNOW-2089107 - local application defaults

- lib/authentication/auth_workload_identity/attestation_aws.ts
- package.json
…n\nMove to Smithy HttpRequest implementation to align with AWS SDK v3 internals.\n- Update import in attestation_aws.ts to use @smithy/protocol-http\n- Replace dependency in package.json (remove @aws-sdk/protocol-http, add @smithy/protocol-http)\n\nNo functional changes; unit and type checks pass.
> deps(aws): replace @aws-sdk/protocol-http with @smithy/protocol-http

- test/integration/testCrl.ts
Not creating restore ticket as the feature is WIP and I'm working on chaning CRLs
> NO-SNOW Disable CRL tests that are failing on GS release pipeline

- .github/workflows/changelog.yml
- CHANGELOG.md
> SNOW-2337823 Add CHANGELOG.md
